// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wwoedehgqxulvbuptyqi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind3b2VkZWhncXh1bHZidXB0eXFpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMjQ1MjUsImV4cCI6MjA2NTkwMDUyNX0.OlbW2xwG7dSYIwt5FgN1yHek_J1zWoxIAEAQuKpQVvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);